# Use the official Python base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /testproject

# Copy the app code to the container
ADD ./ /testproject/

COPY ./requirements.txt /testproject/

RUN apt-get update \
    && apt-get -y install libpq-dev python-dev-is-python3 gcc
# Install the dependencies
RUN pip install -r requirements.txt

# Command to run the tests
CMD pytest -v -s -W ignore --tb=short --color=yes
