version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

  tests:
    build:
      context: ./
      dockerfile: Dockerfile.tests
    depends_on:
      - database
      - api

  database:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: rest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 3
    ports:
      - "5432:5432"
    env_file:
      - ./fastapi1/main_app/.env